export enum ACTION_TYPES {
  SET_CARS = 'SET_CARS',
  SET_TOTAL = 'SET_TOTAL',
  SET_GARAGE_PAGE = 'SET_GARAGE_PAGE',
  ADD_CAR = 'ADD_CAR',
  UPDATE_NEW_CAR_NAME = 'UPDATE_NEW_CAR',
  UPDATE_NEW_CAR_COLOR = 'UPDATE_NEW_CAR_COLOR',
  SET_CAR_TO_UPD_ID = 'SET_CAR_TO_UPD_ID',
  SET_CAR_TO_UPD_NAME = 'SET_CAR_TO_UPD_NAME',
  SET_CAR_TO_UPD_COLOR = 'SET_CAR_TO_UPD_COLOR',
  TOGGLE_IS_UPDATING = 'TOGGLE_IS_UPDATING',
  UPDATE_CARS = 'UPDATE_CARS',
};