export enum ACTION_TYPES {
  SET_CARS = 'SET_CARS',
  SET_GARAGE_PAGE = 'SET_GARAGE_PAGE',
  SET_TOTAL_CARS = 'SET_TOTAL_CARS',
  TOGGLE_IS_FETCHING_CARS = 'TOGGLE_IS_FETCHING_CARS',
  TOGGLE_IS_PREV_GARAGE_PG_AVL = 'TOGGLE_IS_PREV_GARAGE_PG_AVL',
  TOGGLE_IS_NEXT_GARAGE_PG_AVL = 'TOGGLE_IS_NEXT_GARAGE_PG_AVL',
  ADD_CAR = 'ADD_CAR',
};